# Generated by Django 5.0.7 on 2024-07-16 00:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_addotionalservices_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesRadius',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('radius', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='services',
            name='radius',
        ),
    ]
