# Generated by Django 5.0.7 on 2024-07-16 12:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_servicesradius_remove_services_radius'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='type_id',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='serivce_type',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='service_id',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.services'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.servicetime'),
        ),
    ]
