# Generated by Django 5.0.7 on 2024-07-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_servicetime_rename_type_id_appointments_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
